### ISSUE TITLE
Remove appveyor not found badges

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-dashboard#11]
Currently we have two red badges from appveyor, the failing ones and "project not found or access denied" ones. 
The latter needs to be removed from the dashboard as we don't mandate to use appveyor (especially now that other CI platforms offer windows infrastructure).

<img width="867" alt="screen shot 2018-12-24 at 13 41 02" src="https://user-images.githubusercontent.com/6788290/50399736-e5daad00-0781-11e9-9764-3d894d11ec5e.png">

**Comment by astrofrog** [comment]
Done! This is now configurable in the YAML file.
