### ISSUE TITLE
specutils CircleCI badge shows broken link

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-dashboard#17]
Is it just me or does anyone else see a broken link icon for `specutils` under CircleCI column? Clicking on it (https://circleci.com/gh/astropy/specutils) gives me 404 (you need to log in first, blah blah).

**Comment by pllim** [comment]
Did you try logging out from CircleCI? 😉

**Comment by astrofrog** [comment]
Ah the 'free and open source' setting in CircleCI was off. I fixed that.
