### ISSUE TITLE
synphot_refactor appveyor badge missing

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-dashboard#20]
I see `synphot_refactor` in the dashboard webpage but not in the YAML here, so maybe this is a wrong place to report. If so, please tell me where to move this to. `synphot_refactor` has Appveyor CI but its badge is not listed.

**Comment by astrofrog** [comment]
As mentioned on Slack you need to set `appveyor_project: pllim/synphot-refactor` in the YML

**Comment by pllim** [comment]
Ops. I was gonna open PR via web interface (the lazy way) and didn't realize I could commit directly to master, so this was accidentally fixed in 6578d3ed891a321ef0db7e0ec8482ddd6b88b092 .
