### ISSUE TITLE
Include conda badges

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-dashboard#21]
We should add a column which is the conda badge for the anaconda.org/astropy channel. I can try working on that.

**Comment by pllim** [comment]
I see an "anaconda cloud" column now, but it does not do justice to packages that get distributed in `conda-forge` or other alternate channels like `astroconda`. I am afraid people will take that column as "this package is not `conda` installable," which is not the case at all.

**Comment by pllim** [comment]
Also, the "anaconda cloud" icon shows broken link for some packages.

**Comment by astrofrog** [comment]
All packages in the astropy ecosystem should be available in the astropy channel, the fact that some are not is an issue and I opened an issue here: https://github.com/astropy/conda-channel-astropy/issues/175

This dashboard is really just intended for us maintainers, not for users looking at what can be installed with conda.

**Comment by bsipocz** [comment]
@astrofrog - There is a bug in this somewhere. For astropy the version listed on the dashboard is 2.0.11 (I suspect as it was built last), and not the latest 3.1.1 version.

Also, for packages available on the default channel, maybe we should list the version from the defaults channel? Or simply rather say astropy conda in the name of the column?

**Comment by bsipocz** [comment]
(otherwise I'm 👎 on including third party channels like `astroconda` in this picture, even if we extend it to other channels I wouldn't go beyond `astropy`, `defaults`, and `conda-forge`.)

**Comment by astrofrog** [comment]
@bsipocz - the bug is on anaconda.org, it's showing the latest uploaded version. I reported it to them.

I think I'd rather just say 'astropy conda' in the column - this is so we can check the versions we provide. It's not to say we can't add a defaults column too, but most packages aren't in defaults.

**Comment by bsipocz** [comment]
OK, I'm perfectly fine with "astropy conda".
