### ISSUE TITLE
What is Travis CI - Branch and why is it chronically failing?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-dashboard#22]
In the commits in `master`, there is a "Travis CI - Branch" build and it is chronically failing.

Example log: https://github.com/astropy/astropy-dashboard/runs/47835255

**Comment by astrofrog** [comment]
For some reason Travis forgot about the authentication settings I put there...

**Comment by astrofrog** [comment]
Huh well that confused the hell out of me, apparently we have some kind of parallel configuration on travis-ci.com (in addition to travis-ci.org). Maybe it's to do with the shift to GitHub apps.

**Comment by astrofrog** [comment]
It's failing because of the authentication settings being missing on .com but they are in .org so the deploy works fine. Let's ignore this for now.
