### ISSUE TITLE
synphot_refactor now has duplicate entries

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-dashboard#23]
In my attempt to fix #20, the dashboard now has duplicate entries of "synphot_refactor" -- one from website registry and another from the YML here. I don't know how to get rid of the duplicate. (I did one attempt and it was disastrous.)

🙈 

(Yes, you can remove my write access from this repo if you want. The temptation to commit directly to master to see instant rendering is too great!)

**Comment by astrofrog** [comment]
@pllim - just for info, you can easily run the script locally and open the status.html file in a browser to check things :)

**Comment by astrofrog** [comment]
And yeah I need to tidy up some of the hacky code in ``make_status.py`` - part of the confusion is that the main thing that can be used to safely identify duplicates is the repo name not the package name. I'll see if I can clean things up later.

**Comment by pllim** [comment]
Thanks! 😬

**Comment by mwcraig** [comment]
Fix for this incoming this evening....
