### ISSUE TITLE
Have the "coordinated" packages list be derived from the registry

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-dashboard#26]
Once astropy/astropy.github.com#327 is in, we should have this dashboard get the list of what's coordinated and what's affiliated from the registry.json since that's the "official" list.

**Comment by bsipocz** [comment]
what about infrastructure? will those packages make it to the registry?

**Comment by eteq** [comment]
Good question @bsipocz .  I'd say we decide that separately from this one, but the implementation would be straightforward once this is solved, as we could add a field to the json file to indicate which ones are infrastructure.
