### ISSUE TITLE
Wrong rtd badge for projects with mismatching repo and RTD names

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-dashboard#8]
The RTD badges on the dashboard point to the wrong package when the repo name on github is different to the name of the package on RTD. E.g. glue and gala 
Fixing this will probably involve of updates to the registry, too, e.g. adding a ``rtd_url`` or ``rtd_name`` enrt

cc @astrofrog @eteq

**Comment by astrofrog** [comment]
This is now configurable in the YAML file using ``rtd_name``.
